FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libbsd-dev pkg-config libssl-dev

COPY . /repo
WORKDIR /repo
ENV DESTDIR=/install
RUN make -j8 BUNDLED_LIBBSD=1
RUN make install

FROM ubuntu:20.04 as package
COPY --from=builder /install /install
